name: Testes unitários

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
    - name: Setup do Node.js
      uses: actions/setup-node@v2.1.1
    - name: Instalar as dependências do projeto
      run: npm ci
    - name: Executar os testes de unidade
      run: npm test